print("##############################")
print("#                            #")
print("#  Rakhmad Fauzhan Ramadhan  #")
print("#       2310817210021        #")
print("#                            #")
print("##############################")